// PVSCL:IFCOND(Alphabetical, LINE)
    themes.sort((a, b) => a.name.localeCompare(b.name))
    // PVSCL:ENDCOND// PVSCL:IFCOND(Alphabetical, LINE)
        result = a.name.localeCompare(b.name)
        // PVSCL:ELSEIFCOND(Number, LINE)
        result = parseFloat(a.name) > parseFloat(b.name)
        // PVSCL:ELSEIFCOND(Date, LINE)
        // PVSCL:ENDCOND// PVSCL:IFCOND(Alphabetical, LINE)
      codes = codes.sort((a, b) => a.name.localeCompare(b.name))
      // PVSCL:ENDCOND